### ISSUE TITLE
Multiple error messages; mining does not work

### ISSUE THREAD

**Issue by torusta** [open-orchard/koinos-gui-miner#106]
### When running the miner I first got these issues after about 5-10min run time

"There was a problem retrieving the KOIN balance."

"There was a problem retrieving the Ether balance."

As far as I can see I got everything set up correctly. Funding and recipient addresses are different. 

### After restarting the miner I am sometimes getting these additional error messages 

"Failed to retrieve the start time from the token mining contract."

"Could not retrieve the PoW height."

![Untitl4ed](https://user-images.githubusercontent.com/72689139/95897333-a5508700-0d8d-11eb-8ec3-35e4c2d02df2.jpg)

**Comment by followbtcnews** [comment]
Yep, I have same exact errors running on Windows 10 pro

**Comment by tandarae** [comment]
Same here. Windows 10.  Mining starts then get these messages and stops.

- could not retrieve the PoW height
- problem retrieving the KOIN balance

Also got this once: Failed to check for transaction receipt: {“data”: null}

**Comment by followbtcnews** [comment]
try changing your endpoint to http://mining.koinos.io/   I am trying it now and so far so good

**Comment by sgerbino** [comment]
We have noticed issues with the default endpoint. Try what @followbtcnews recommands; we set up an endpoint that seems to work better: http://mining.koinos.io

**Comment by lykos1974** [comment]
Had the issues mentioned by OP , tried what @followbtcnews and now i get a message "Returned error: insufficient funds for gas * price + value" . I have proof frequenct set to 240 and my ETH balance is 0.02 ETH .

**Comment by followbtcnews** [comment]
> Had the issues mentioned by OP , tried what @followbtcnews and now i get a message "Returned error: insufficient funds for gas * price + value" . I have proof frequenct set to 240 and my ETH balance is 0.02 ETH .

Please dont set frequency at 240 , you will go thru your eth paying gas fees very very fast. try between 1-24 for first few days

**Comment by aaedx** [comment]
Exact same issues as OP and others. Will try using  http://mining.koinos.io as others have suggested. Thanks!

**Comment by torusta** [comment]
after setting it to http://mining.koinos.io  it ran for about 90 mins before giving me another error. Has anyone else had success with switching the endpoint?

**Comment by drov0** [comment]
Getting "there was a problem retrieving the ether balance" on  http://mining.koinos.io as well. 

Can you use multiple miners on the same address ?

**Comment by lazydba247** [comment]
@drov0, @aaedx open a **free** account in https://infura.io/
and you get a wss://  endpoint with 100,000 requests for 24H
no issue since i used it.

**Comment by mahamb** [comment]
I am getting the same error.
Errors:
Failed to check for transaction receipt
There was a problem retrieving the Ether Balance

Ethereum EndPoint: http://mining.koinos.io.
Frequency: 24 per day (initial for testing)
Ether Balance: .2

OS: Win10 Pro
Ver: 1803

Disabled Firewall and AntiMalware but still getting errors.

Seems having issues on Windows 10 OS.

**Comment by mahamb** [comment]
suggestion from lazydba247.
creating account in https://infura.io/ works for me.
Thanks.

**Comment by ghostantin** [comment]
> Same here. Windows 10. Mining starts then get these messages and stops.
> 
> * could not retrieve the PoW height
> * problem retrieving the KOIN balance
> 
> Also got this once: Failed to check for transaction receipt: {“data”: null}

I also got the transaction receipt error, but it seems it works ok after clicking "close"

**Comment by mahamb** [comment]
Does it support GPU or can only mine using CPU?

**Comment by ghostantin** [comment]
Did you get any tokens in your wallet? I see that some payments are carried out but I didn't receive anything yet. https://etherscan.io/token/0x66d28cb58487a7609877550E1a34691810A6b9FC

**Comment by torusta** [comment]
The miner seems to work for me now; I only changed the endpoint to  http://mining.koinos.io 

But otherwise I will try what @lazydba247  suggested

Thanks for the engagement everyone

**Comment by sgerbino** [comment]
Please download and retry with the new release: https://github.com/open-orchard/koinos-gui-miner/releases/tag/1.0.1
Feel free to re-open this issue if the problem persists. Thanks.
