### ISSUE TITLE
Could not retrieve the PoW height.

### ISSUE THREAD

**Issue by Santigs** [open-orchard/koinos-gui-miner#107]
After a while of working, the miner stops and gives me  this error message

**Comment by clarkinelli** [comment]
I have received this message 4 times in last 2 hrs keeps getting more frequent

**Comment by sgerbino** [comment]
Please download and retry with the new release: https://github.com/open-orchard/koinos-gui-miner/releases/tag/1.0.1
Feel free to re-open this issue if the problem persists. Thanks.

**Comment by clarkinelli** [comment]
I am unable to open koinos miner on my windows computer.  It was running this morning when I left computer is still on and all other programs running.  At some point miner turned off and I can not read open.  I tried shutting down and restarting this obviously did not work. 

I look forward to your response.

Ryan
