### ISSUE TITLE
There was a problem retrieving the KOIN balance.

### ISSUE THREAD

**Issue by cryptoPD** [open-orchard/koinos-gui-miner#110]
There was a problem retrieving the KOIN balance.
What does that mean?

**Comment by michaelcamire** [comment]
I keep getting the same error after running 3 minutes.

**Comment by clarkinelli** [comment]
I received once but after login back in have not received this error message again. However I keep getting "Could not retrieve the PoW height."

**Comment by cryptoPD** [comment]
Now I am getting "there is a problem retrieving the Ether balance"

**Comment by lazydba247** [comment]
open a free account in https://infura.io/
and you get a wss:// endpoint with 100,000 requests for 24H
no issue since i used it.

**Comment by sgerbino** [comment]
Please download and retry with the new release: https://github.com/open-orchard/koinos-gui-miner/releases/tag/1.0.1
Feel free to re-open this issue if the problem persists. Thanks.
