### ISSUE TITLE
Proof Frequency settings and Restarting the miner

### ISSUE THREAD

**Issue by mahamb** [open-orchard/koinos-gui-miner#119]
Is it ok to set the proof of frequency to 1 per week? Or the transactions / PoW will be expired?
If restarting the miner, what happens to the PoW transactions that were not sent/submitted yet?

I received below message after I stopped the miner with 2 per week Proof Frequency and started again with 192 Proof Frequency to verify if the earlier transactions will still be collected if I restarted the miner.

"Transaction was not mined within 50 blocks, please make sure your transaction as properly sent. Be aware that in might still be mined."

OS: Windows 10
Miner Version: 1.0.1

**Comment by sgerbino** [comment]
> Is it ok to set the proof of frequency to 1 per week? Or the transactions / PoW will be expired?
> If restarting the miner, what happens to the PoW transactions that were not sent/submitted yet?
> 

It is not a problem to set proof frequency to once per work. Once the proof is found it is submitted. Proof frequency just alters the difficulty level.

> I received below message after I stopped the miner with 2 per week Proof Frequency and started again with 192 Proof Frequency to verify if the earlier transactions will still be collected if I restarted the miner.
> 
> "Transaction was not mined within 50 blocks, please make sure your transaction as properly sent. Be aware that in might still be mined."
> 

This indicates that the transaction is taking longer than normal to be mined in to a block. The gas fees could be spiking at that particular time for example.

> OS: Windows 10
> Miner Version: 1.0.1
